module.exports = [
  {
    airline: 'British Airways',
    airlineCode: 'BA',
    dealCode: 'TIE08',
    serial: 1,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Kenya Airways',
    airlineCode: 'KQ',
    dealCode: 'IQUA28',
    serial: 2,
    dealOps: 'rate',
    mark: 'down',
    figure: 0,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  }, {
    airline: 'Etihad',
    airlineCode: 'EY',
    dealCode: '',
    serial: 4,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {

    airline: 'Emirates',
    airlineCode: 'EK',
    dealCode: '',
    serial: 5,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Ethiopian AIr',
    airlineCode: 'ET',
    dealCode: '',
    serial: 6,
    dealOps: 'rate',
    mark: 'down',
    figure: 8,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Egypt AIr',
    airlineCode: 'MS',
    dealCode: '',
    serial: 7,
    dealOps: 'rate',
    mark: 'down',
    figure: 9,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Royal Jordanian',
    airlineCode: 'RJ',
    dealCode: '',
    serial: 8,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
  }, {
    airline: 'Delta',
    airlineCode: 'DL',
    dealCode: '',
    serial: 9,
    dealOps: 'rate',
    mark: 'down',
    figure: 9,
    destination: [
      'all',
    ],
    travelClass: [
      'Y',
      'B',
      'M',
      'S',
      'H',
      'Q',
      'K',
      'L',
      'U',
    ],
    travelClassException: [],
    destinationException: [
      'IAH',
      'HOU',
    ],
  },
  {
    airline: 'Delta',
    airlineCode: 'DL',
    dealCode: '',
    serial: 10,
    dealOps: 'rate',
    mark: 'down',
    figure: 0,
    destination: [
      'IAH',
      'HOU',
    ],
    travelClass: [
      'C',
      'J',
      'D',
      'I',
      'Z',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Delta',
    airlineCode: 'DL',
    dealCode: '',
    serial: 11,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'IAH',
      'HOU',
    ],
    travelClass: [
      'T',
      'X',
      'V',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'United',
    airlineCode: 'UA',
    dealCode: '',
    serial: 12,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Turkish Airlines',
    airlineCode: 'TK',
    dealCode: '',
    serial: 13,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Asky',
    airlineCode: 'KP',
    dealCode: '',
    serial: 14,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Rwandair',
    airlineCode: 'WB',
    dealCode: '',
    serial: 15,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Alitalia',
    airlineCode: 'AZ',
    dealCode: '',
    serial: 16,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Iberia',
    airlineCode: 'IB',
    dealCode: '',
    serial: 18,
    dealOps: 'rate',
    mark: 'down',
    figure: 0,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Arik Air',
    airlineCode: 'W3',
    dealCode: '',
    serial: 19,
    dealOps: 'rate',
    mark: 'down',
    figure: 0,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Air France',
    airlineCode: 'AF',
    dealCode: '',
    serial: 20,
    dealOps: 'fixed',
    mark: 'up',
    figure: 3000,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'KLM',
    airlineCode: 'KL',
    dealCode: '',
    serial: 21,
    dealOps: 'fixed',
    mark: 'up',
    figure: 3000,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Royal Air Maroc',
    airlineCode: 'AT',
    dealCode: '',
    serial: 22,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'South African Airways',
    airlineCode: 'SA',
    dealCode: '',
    serial: 23,
    dealOps: 'rate',
    mark: 'down',
    figure: 3,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Lufthansa',
    airlineCode: 'LH',
    dealCode: 'TIC01',
    serial: 3,
    dealOps: 'rate',
    mark: 'down',
    figure: 5,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [
      'F',
      'A',
      'P',
      'Y',
      'Q',
      'V',
    ],
    destinationException: [],
  }, {
    airline: 'Virgin',
    airlineCode: 'VS',
    dealCode: '',
    serial: 17,
    dealOps: 'rate',
    mark: 'down',
    figure: 0,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
  {
    airline: 'Qatar',
    airlineCode: 'QR',
    dealCode: '',
    serial: 24,
    dealOps: 'rate',
    mark: 'up',
    figure: 3,
    destination: [
      'all',
    ],
    travelClass: [
      'all',
    ],
    travelClassException: [],
    destinationException: [],
  },
];
